apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache-log-storage-claim
  namespace: factorial
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-storage
